### ISSUE TITLE
does not exist in schema defination

### ISSUE THREAD

**Issue by fozerol** [thake/logminer-kafka-connect#8] opened 2020-10-26 06:35 UTC
Linux / Oracle 11.2.0.4.0 
throws this error below is log file. this is test table and contains ID,NAME,VALUE fields when i try it another test table it throws same error with first column name
[2020-10-26 06:33:00,247] INFO [Producer clientId=connector-producer-logminer-kafka-connect-0] Cluster ID: VHytdJxoQauJ6sQygxw07w (org.apache.kafka.clients.Metadata:279)
[2020-10-26 06:33:00,298] INFO Oracle Kafka Connector is starting (com.github.thake.logminer.kafka.connect.SourceTask:191)
[2020-10-26 06:33:00,628] INFO Connected to database at 192.168.50.5:1521/KKBS2 (com.github.thake.logminer.kafka.connect.SourceTask:30)
[2020-10-26 06:33:00,629] INFO WorkerSourceTask{id=logminer-kafka-connect-0} Source task finished initialization and start (org.apache.kafka.connect.runtime.WorkerSourceTask:233)
[2020-10-26 06:33:00,860] INFO Determined current scn of database as 6599498893474 (com.github.thake.logminer.kafka.connect.initial.SelectSource:50)
[2020-10-26 06:33:00,862] INFO Getting dictionary details for table : TableId(owner=flixbus, table=fatih_test2) (com.github.thake.logminer.kafka.connect.SchemaService:39)
[2020-10-26 06:33:00,900] INFO WorkerSourceTask{id=logminer-kafka-connect-0} Committing offsets (org.apache.kafka.connect.runtime.WorkerSourceTask:478)
[2020-10-26 06:33:00,900] INFO WorkerSourceTask{id=logminer-kafka-connect-0} flushing 0 outstanding messages for offset commit (org.apache.kafka.connect.runtime.WorkerSourceTask:495)
[2020-10-26 06:33:00,901] ERROR WorkerSourceTask{id=logminer-kafka-connect-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:187)
java.lang.IllegalStateException: Column ID does not exist in schema definition
        at com.github.thake.logminer.kafka.connect.initial.TableFetcher.poll(TableFetcher.kt:45)
        at com.github.thake.logminer.kafka.connect.initial.SelectSource.poll(SelectSource.kt:58)
        at com.github.thake.logminer.kafka.connect.StartedState$poll$2.invoke(SourceTask.kt:134)
        at com.github.thake.logminer.kafka.connect.StartedState.poll(SourceTask.kt:140)
        at com.github.thake.logminer.kafka.connect.SourceTask.poll(SourceTask.kt:206)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.poll(WorkerSourceTask.java:289)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:256)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:185)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:235)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by thake** [comment] 2020-10-26 07:09
@fozerol Can you provide the DDL for the table in question? I would like to create a Unit test to check this issue.

**Comment by fozerol** [comment] 2020-10-26 07:15
switching back to test table, btw enabled trace to determine whether is there any sql exception
select t.*,rowid , ora_rowscn from flixbus.fatih_test2 as of scn 6599497757352 t  order by rowid asc;
this query runs with success.

CREATE TABLE TESTSCHEMA.FATIH_TEST2
(
  ID     NUMBER                                 NOT NULL,
  NAME   VARCHAR2(50 BYTE),
  VALUE  NUMBER
)
TABLESPACE KKBS2
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX TESTSCHEMA.FATIH_TEST2_PK ON TESTSCHEMA.FATIH_TEST2
(ID)
LOGGING
TABLESPACE KKBS2
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE TESTSCHEMA.FATIH_TEST2 ADD (
  CONSTRAINT FATIH_TEST2_PK
  PRIMARY KEY
  (ID)
  USING INDEX TESTSCHEMA.FATIH_TEST2_PK
  ENABLE VALIDATE);

and exception part of log

java.lang.IllegalStateException: Column ID does not exist in schema definition
        at com.github.thake.logminer.kafka.connect.initial.TableFetcher.poll(TableFetcher.kt:45)
        at com.github.thake.logminer.kafka.connect.initial.SelectSource.poll(SelectSource.kt:58)
        at com.github.thake.logminer.kafka.connect.StartedState$poll$2.invoke(SourceTask.kt:134)
        at com.github.thake.logminer.kafka.connect.StartedState.poll(SourceTask.kt:140)
        at com.github.thake.logminer.kafka.connect.SourceTask.poll(SourceTask.kt:206)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.poll(WorkerSourceTask.java:289)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:256)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:185)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:235)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by thake** [comment] 2020-10-26 14:23
@fozerol I created a test case that tries to reproduce your issue. However, this was not successful. The test case with your table structure succeeds. Can you check if the db user you are using can read the schema tables SYS.ALL_TAB_COLUMNS and SYS.ALL_COL_COMMENTS?

**Comment by fozerol** [comment] 2020-10-26 14:38
Yes, i do confirm user can read those tables also tried with another user  who has dba role also failed with same error.,
I think i found the problem. i had typed table.whitelist = lowercase_table_name , when i changed it to upper case i have no more that error but i have this one 
org.apache.kafka.connect.errors.ConnectException: Tolerance exceeded in error handler
        at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:196)
        at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execute(RetryWithToleranceOperator.java:122)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.convertTransformedRecord(WorkerSourceTask.java:311)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.sendRecords(WorkerSourceTask.java:340)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:264)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:185)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:235)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.kafka.connect.errors.DataException: BigDecimal has mismatching scale value for given Decimal schema
        at org.apache.kafka.connect.data.Decimal.fromLogical(Decimal.java:68)
        at org.apache.kafka.connect.json.JsonConverter$13.toJson(JsonConverter.java:209)
        at org.apache.kafka.connect.json.JsonConverter.convertToJson(JsonConverter.java:617)
        at org.apache.kafka.connect.json.JsonConverter.convertToJson(JsonConverter.java:704)
        at org.apache.kafka.connect.json.JsonConverter.convertToJsonWithEnvelope(JsonConverter.java:592)
        at org.apache.kafka.connect.json.JsonConverter.fromConnectData(JsonConverter.java:346)
        at org.apache.kafka.connect.storage.Converter.fromConnectData(Converter.java:63)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.lambda$convertTransformedRecord$1(WorkerSourceTask.java:311)
        at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndRetry(RetryWithToleranceOperator.java:146)
        at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:180)

**Comment by thake** [comment] 2020-10-27 07:38
@fozerol The error is a duplicate of #2 and is already fixed in the newest version. Can you make sure that you use the latest release? If your problem is not solved with the latest release, please open a separate issue.

Added documentation to state that table.whitelist is case sensitive with b4e0b2d117648b2398b514957d2569b88a271a12. Closing this issue as the original issue has been resolved.

**Closed as completed by thake** 2020-10-27 07:38 UTC
